version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto11
#  pre_build:
#    commands:
#      - echo In the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - java -version
      - ./gradlew build
      - ./gradlew test
  post_build:
    commands:
      - echo Build completed on `date`
      - mv build/libs/macro-0.0.1-SNAPSHOT.jar .
artifacts:
  files:
    - macro-0.0.1-SNAPSHOT.jar
